M48
; DRILL file {KiCad 9.0.6} date 2026-01-03T23:52:16+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-03T23:52:16+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X101.7Y-90.4
X126.3Y-136.0
X182.4Y-89.4
X186.5Y-136.0
M30
